[compute_platform]
type = "cuda"

[compute_platform.cuda]
version = "13.0.3"

[pytorch]
version = "2.12.1"
extra_packages = ["torchvision==0.27.1"]

[comfyui]
version = "0.4.0"
install_manager = false

[build]
platforms = ["linux/amd64"]
