"""Single code authority for exact release-owned toolchain identities."""

UV_VERSION = "0.11.28"
UV_RUNTIME_REQUIREMENT = f"uv=={UV_VERSION}"
UV_BUILD_REQUIREMENT = f"uv_build=={UV_VERSION}"
UV_IMAGE_REPOSITORY = "ghcr.io/astral-sh/uv"
COMFYUI_REPOSITORY = "https://github.com/comfyanonymous/ComfyUI.git"
DEFAULT_MANAGED_PYTHON_VERSION = "3.13.14"
FALLBACK_MANAGED_PYTHON_VERSION = "3.12.13"
CUDA_VERSION = "13.0.3"
CUDA_IMAGE_REPOSITORY = "nvidia/cuda"
CUDA_IMAGE_FLAVOR = "cudnn-devel"
BASE_IMAGE_DISTRO = "ubuntu24.04"
TARGET_PLATFORM = "linux/amd64"
PYTORCH_CHANNEL = "cu130"
PYTORCH_VERSION = "2.12.1"
TORCHVISION_VERSION = "0.27.1"
