"""Single code authority for exact release-owned toolchain identities."""

UV_VERSION = "0.11.28"
UV_RUNTIME_REQUIREMENT = f"uv=={UV_VERSION}"
UV_BUILD_REQUIREMENT = f"uv_build=={UV_VERSION}"
UV_IMAGE_REPOSITORY = "ghcr.io/astral-sh/uv"
COMFYUI_REPOSITORY = "https://github.com/comfyanonymous/ComfyUI.git"
# v0.11.0 is the first formal release to declare its runtime requests dependency.
COMFYUI_MINIMUM_VERSION = "0.11.0"
COMFYUI_FLOOR_COMMIT = "09725967cf76304371c390ca1d6483e04061da48"
# v1.7.0 provides the complete isolated-tool/workspace-Python bridge we require.
COMFY_CLI_MINIMUM_VERSION = "1.7.0"
CDH_VERSION = "0.5.0"
PIP_VERSION = "26.1.2"
DEFAULT_MANAGED_PYTHON_VERSION = "3.13.14"
FALLBACK_MANAGED_PYTHON_VERSION = "3.12.13"
CUDA_VERSION = "13.0.3"
CUDA_IMAGE_REPOSITORY = "nvidia/cuda"
CUDA_IMAGE_FLAVOR = "cudnn-devel"
BASE_IMAGE_DISTRO = "ubuntu24.04"
TARGET_PLATFORM = "linux/amd64"
PYTORCH_CHANNEL = "cu130"
PYTORCH_VERSION = "2.12.1"
TORCHVISION_VERSION = "0.27.1"
CUDA_PROTECTED_REQUIREMENTS = ("torch", "torchaudio", "torchvision")
